name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build libtbb-dev
    - name: Setup GCC
      if: matrix.compiler == 'gcc'
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 100
    - name: Setup Clang
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get install -y clang
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DOOZE_BUILD_REGTESTS=On
    - name: Build
      run: cmake --build build
    - name: Regtests
      run: ./tools/run_regtests.py -e build/regtest/regtest
